name: Check XAML Formatting
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'pipelines'
      - '**-servicing'
  pull_request:
    branches:
      - 'main'
      - '**-servicing'
    paths:
      - '**.xaml'

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Xaml Styler
        shell: pwsh
        run: |
          cd $env:GITHUB_WORKSPACE
          git diff --name-only HEAD~1..HEAD