name: Check XAML Formatting
on:
  push:
    branches:
      - 'main'
      - 'pipelines'
      - '**-servicing'
    paths:
      - '**.xaml'
  pull_request:
    branches:
      - 'main'
      - '**-servicing'
    paths:
      - '**.xaml'

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Install Xaml Styler
        shell: powershell
        run: |
          $changedFiles = (git diff --name-only) -split "\n" | Where-Object {$_ -like "*.xaml"}
          dotnet tool install --global XamlStyler.Console
          xstyler -p -f $changedFiles